import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// Builds a single JS + CSS bundle with stable file names into ../docs/tools,
// which clock.html and compass.html (generated by ../build.py) reference.
export default defineConfig({
  plugins: [react({ babel: { plugins: ['styled-jsx/babel'] } })],
  base: './',
  publicDir: false,
  build: {
    outDir: '../docs/tools',
    emptyOutDir: true,
    rollupOptions: {
      input: 'src/main.jsx',
      output: {
        format: 'iife',
        inlineDynamicImports: true,
        entryFileNames: 'app.js',
        chunkFileNames: 'chunk-[name].js',
        assetFileNames: (a) => (a.name && a.name.endsWith('.css') ? 'app.css' : 'asset-[name][extname]'),
      },
    },
  },
});
